# When is the finally block executed?

# A finally block always executes, regardless of whether an exception is thrown. The following code example uses a try / catch block to catch 
# an ArgumentOutOfRangeException. The Main method creates two arrays and attempts to copy one to the other.